# Generated by Django 4.2.1 on 2023-08-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triner',
            fields=[
                ('triner_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
